
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - image: okteto.dev/ping:dev
        name: ping

---

apiVersion: v1
kind: Service
metadata:
  name: ping
spec:
  type: LoadBalancer
  ports:
  - name: ping
    port: 8080
  selector:
    app: ping